scrape_configs:
  - job_name: 'CLIENTE_1'
    scrape_interval: 30s
    static_configs:
      - targets: ['192.168.3.74:8080/q']
remote_write:
  - url: "http://localhost:9200/api/v1/write"
    write_relabel_configs:
      - source_labels: ['metrics']
        regex: 'metric_app'
        action: keep